baseurl = "/"
languageCode = "en-us"
title = "The code behind the visuals"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
relativeurls = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/giocomai/EdjNet-blog"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/giocomai"

[params]
    description = "The codebase"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
